spring:
  application:
    name: api-gateway

  config:
    import: classpath:logging.yml, classpath:route.yml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8010/realms/microservice

server:
  port: 8008

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8004/eureka/

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: TRACE
