spring:
  application:
    name: api-gateway

  config:
    import: classpath:logging.yml, classpath:route.yml

server:
  port: 8008

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8004/eureka/

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
    org.springframework.cloud.gateway: TRACE


